---
apiVersion: v1
kind: Service
metadata:
  name: my-demo-service
spec:
  type: NodePort
  selector:
    app: demo
  ports:
    - protocol: TCP
      nodePort: 30003
      port: 8888
      targetPort: 8888
#
