name: Go hello package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.17

      - name: Build
        run: docker image build -t myhello:1.0 ./hello

      - name: Tag Image
        run: docker image tag myhello:1.0 juharov/myhello:1.0

      - name: Push Image
        run: docker image push docker.io/juharov/myhello:1.0


